## DDOL_entropy.R by Maggie Wilson and Rohan Maddamsetti.
library(tidyverse)

## IMPORTANT TODO: make a plot of plasmid distribution in each genome,
## showing all plasmids (gray out the ones without symbiosis genes.)

## get mobility data for all plasmids, generated by parse-MOBtyper-results.py.
plasmid.mobility.data <- read.csv("../results/mobility-results.csv")

## Get the length of each plasmid, and number of proteins on them.
plasmid.metadata <- read.csv("../results/replicon-lengths-and-protein-counts.csv") %>%
    filter(SeqType == "plasmid") %>%
    ## rename the Annotation_Accession column for merging with pathway data.
    rename(Annotation_Accession = AnnotationAccession) %>%
    ## replace prefixes.
    mutate(Plasmid = str_replace(SeqID, "N[CZ]_","")) %>%
    ## join the mobility results.
    left_join(plasmid.mobility.data)


## get the plasmid distribution entropy calculation results.
entropy.data <- read.csv("../results/entropy_data.csv")

## Get the count of genes in each pathway on each plasmid.
NifFix.pathway.count.df <- read.csv("../results/NifFixPlasmidCount.csv")
Nod.pathway.count.df <- read.csv("../results/NodPlasmidCount.csv")
T3SS.pathway.count.df <- read.csv("../results/T3SSPlasmidCount.csv")
All.symbiosis.pathways.count.df <- read.csv("../results/AllPathwaysPlasmidCount.csv")

## and merge into a big dataframe for analysis.
pathway.plasmid.count.df <- NifFix.pathway.count.df %>%
    full_join(Nod.pathway.count.df) %>%
    full_join(T3SS.pathway.count.df) %>%
    full_join(All.symbiosis.pathways.count.df) %>%
    ## add plasmid metadata.
    left_join(plasmid.metadata)


## plot PathwayGeneCount versus Predicted Mobility
mobility.plot1 <- pathway.plasmid.count.df %>%
    ## only plot plasmids with symbiosis genes
    filter(PathwayGeneCount > 0) %>%
    ggplot(aes(x = PredictedMobility, y = PathwayGeneCount)) +
    facet_grid(.~PathwayType) +
    geom_boxplot() +
    theme_classic()

mobility.plot1

## plot distribution of mobilities for plasmids with and without symbiosis genes
mobility.plot2 <- pathway.plasmid.count.df %>%
    mutate(SymbiosisPlasmid = ifelse(PathwayGeneCount > 0, TRUE, FALSE)) %>%
    ggplot(aes(x = PredictedMobility)) +
    facet_grid(PathwayType~SymbiosisPlasmid) +
    geom_bar() +
    theme_classic()

mobility.plot2



## count the number of genes found on plasmids in each pathway
## in each genome.
genome.pathway.gene.count <- pathway.plasmid.count.df %>%
    group_by(Annotation_Accession, PathwayType) %>%
    summarize(TotalPathwayGeneCount = sum(PathwayGeneCount)) %>%
    ungroup()

## rank the genomes by the number of genes found on plasmids
## over all three symbiosis pathways.
genome.all.pathways.ranking <- genome.pathway.gene.count %>%
    filter(PathwayType == "All Symbiosis Pathways") %>%
    ## arrange by total number of symbiosis genes.
    arrange(desc(TotalPathwayGeneCount)) %>%
    ## rank by total number of symbiosis genes.
    mutate(GenomeRank = rank(desc(TotalPathwayGeneCount),ties.method="first")) %>%
    ## drop the PathwayType column for nice merging downstream.
    select(-PathwayType) %>%
    ungroup()

## rank the plasmids containing symbiosis genes in each genome by plasmid length.
symbiosis.plasmid.ranking <- pathway.plasmid.count.df %>%
    filter(PathwayType == "All Symbiosis Pathways") %>%
    ## remove plasmids with no symbiosis genes from the ranking.
    filter(PathwayGeneCount > 0) %>%
    ## rank plasmids containing symbiosis plasmids within each genome based on size.  
    group_by(Annotation_Accession) %>%
    mutate(PlasmidLengthRank = rank(desc(replicon_length),ties.method="first")) %>%
    ## turn PlasmidLengthRank into a factor for plotting.
    mutate(PlasmidLengthRank = as.factor(PlasmidLengthRank)) %>%
    ## for nice merging downstream, we don't want to have the PathwayGeneCount.
    select(Annotation_Accession, Plasmid, replicon_length, protein_count, PlasmidLengthRank) %>%
    ungroup()
  

## add the genome ranks to pathway.plasmid.count.df for plotting.
pathway.plasmid.count.plot.df <- pathway.plasmid.count.df %>%
    ## CRITICAL: remove plasmids with no symbiosis genes from the plot
    ## THIS IS NEEDED FOR CONSISTENCY WITH plasmid.all.pathway.ranking!
    filter(PathwayGeneCount > 0) %>%
    ## add the genome ranking.
    left_join(genome.all.pathways.ranking) %>%
    ## add the plasmid ranking.
    left_join(symbiosis.plasmid.ranking)


stacked.pathway.profile.plot <- pathway.plasmid.count.plot.df %>%
    ggplot(aes(x=GenomeRank, y = PathwayGeneCount, fill=PlasmidLengthRank)) +
    geom_bar(stat="identity") +
    theme_classic() +
    theme(legend.position="top") +
    facet_grid(PathwayType~.)

stacked.pathway.profile.plot
ggsave("../results/DDOL-pathway-profile.pdf", stacked.pathway.profile.plot, width=8, height = 11)

stacked.pathway.mobility.plot <- pathway.plasmid.count.plot.df %>%
    ggplot(aes(x=GenomeRank, y = PathwayGeneCount, fill=PredictedMobility)) +
    geom_bar(stat="identity") +
    theme_classic() +
    theme(legend.position="top") +
    facet_grid(PathwayType~.)

stacked.pathway.mobility.plot
ggsave("../results/DDOL-pathway-mobility.pdf", stacked.pathway.mobility.plot, width=8, height = 11)




entropy.rank.data <- entropy.data %>%
  group_by(PathwayType) %>%
    mutate(EntropyRank = rank(desc(Entropy), ties.method = "first")) %>%
    ## join the genome ranking data.
    left_join(genome.all.pathways.ranking)


entropy.plot <- entropy.rank.data %>%
    ggplot(aes(x=EntropyRank, y=Entropy, color=PathwayType)) + 
  geom_point(size=1, alpha =.75) + facet_grid(PathwayType~.) +
  theme_classic() + guides(color="none")
ggsave("../results/DDOL-entropy.pdf", entropy.plot, width=8, height = 11)


entropy.of.ranked.genomes.plot <- entropy.rank.data %>%
    ggplot(aes(x = GenomeRank, y=Entropy)) +
    geom_point(size=0.2, alpha =.75) + facet_grid(PathwayType~.) +
    theme_classic()

entropy.of.ranked.genomes.plot
ggsave("../results/genome-ranked-entropy.pdf", entropy.of.ranked.genomes.plot, width=8, height = 11)

## make a plot of entropy and number of genes in the pathway.
entropy.versus.pathway.genes.plot <- entropy.rank.data %>%
    ggplot(aes(x = TotalPathwayGeneCount, y=Entropy)) +
    geom_point(size=0.2, alpha =.75) + facet_grid(.~PathwayType) +
    theme_classic()

entropy.versus.pathway.genes.plot

